arrays

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])

In [5]:
print(arr)

[1 2 3 4]


In [6]:
a=[1,2,3,4,"hello"]
a #all elements are stored in arrays as unicode or string DT

[1, 2, 3, 4, 'hello']

In [7]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

vectors : stored in 1 dimensional space

matrix : elements stored in 2 dimensions of rows and columns

In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mat=np.array(l)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array generation

Range function: arange(start,stop,steps,dtype) --> generates arrays

In [11]:
arr=np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


array whose all elements are zeros:

In [12]:
arr=np.zeros(6) #1d matrix with elements 0
print(arr)

[0. 0. 0. 0. 0. 0.]


In [13]:
arr=np.zeros((6,6)) #6x6 matrix with all elements 0
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


arrays of 1s

In [14]:
arr=np.ones(7)
print(arr)

[1. 1. 1. 1. 1. 1. 1.]


In [15]:
arr=np.ones((6,6))
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


linspace(start,stop,num) --> returns evenly spaced numbers over an interval

nums --> no. of elements between

In [16]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Random generation functions : using random library

import random as rand

In [17]:
import random as rand

In [18]:
arr=np.random.rand(10)
arr

array([0.4300418 , 0.56520147, 0.78211362, 0.75836737, 0.70844585,
       0.00720263, 0.95698357, 0.04277314, 0.02595981, 0.89957203])

randn() -->standardized form of elements --> in range of -3 to 3

In [19]:
arr=np.random.randn(10)
arr

array([-1.17584496, -2.75780719, -1.28419486,  1.15681495, -0.16771569,
        1.33980228, -0.17733781,  0.02916633,  0.13058895,  1.76621244])

randint(lowpt,highpt,size) --> generates a random no. between a given range

In [20]:
arr=np.random.randint(6,21,10,int)
arr


array([ 9,  6, 15,  7, 20, 17, 15, 20, 11,  7], dtype=int32)

Array attributes:
attributes : variables defined inside a class

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape #shape is an attribute therefore we dont use brackets"()""

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

Array methods:

minimum 

|maximum

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()


np.int64(1)

In [27]:
arr.max()

np.int64(9)

array operations

axis = 0 -->sum of columns

axis = 1 --> sum of rows

In [28]:
arr.sum()

np.int64(45)

In [29]:
sum=arr.sum(axis=0)
sum #sum of all elements


array([12, 15, 18])

In [30]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [31]:
arr.mean()

np.float64(5.0)

In [32]:
arr.std()

np.float64(2.581988897471611)

In [33]:
arr.argmax() #gives index of largest element

np.int64(8)

In [34]:
arr.argmin() #gives index of smallest element

np.int64(0)

Reshaping and Resizing

In [37]:
import numpy as np

In [38]:
arr=np.arange((1,31))
arr

TypeError: arange: scalar arguments expected instead of a tuple.