Array manipulation

stacking

you can't stack 2 arrays

In [1]:
import numpy as np

In [8]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])

In [9]:
A

array([1, 2, 3, 4])

In [10]:
B

array([5, 6, 7, 8])

Vertical stacking

A and B are passed in form of tuple

In [12]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

horizontal stack

In [13]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8])

column stack

In [16]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting arrays

In [18]:
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

np.hsplit(array , no. of splits)-->hsplit splits array horizontally

In [21]:
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

vsplit() -->splits array horizontally

In [ ]:
arr=np.vsplit(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [27]:
for i in arr:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
