In [70]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

get shape of matrix

In [71]:
data.shape

(5, 3)

find average aage of students

In [72]:
np.mean(data[:,0])

np.float64(18.4)

extract math marks

In [73]:
mm=data[:,1]

In [74]:
mm

array([85, 92, 76, 65, 90])

find the highest science marks

In [75]:
sm=data[:,2]
sm

array([78, 88, 95, 70, 85])

In [76]:
np.max(sm)

np.int64(95)

get the student deatils who scored above 90 in math

In [77]:
data[data[:,1]>90]

array([[19, 92, 88]])

increase math marks of all students by 5


In [78]:
new_math=data[:,1]+5
new_math

array([90, 97, 81, 70, 95])

find students younger than 18

In [79]:
data[data[:,0]<19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [80]:
print(len(data[data[:,0]<19]))

3


average marks in each subject

In [81]:
np.mean(data[:,1])

np.float64(81.6)

In [82]:
np.mean(data[:,2])

np.float64(83.2)

In [83]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

students scored atleast 80 in both sub

In [84]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

replace all science marks less than 75 with 0

In [87]:
data[:,2][data[:,2]<75]=0

In [88]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])